name: CMake

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Build on Linux.
        if: runner.os == 'Linux'
        run: |
          echo Will build on ${{runner.os}}.
          sh build_unix.sh
          
      - name: Build on Windows.
        if: runner.os == 'Windows'
        run: |
          echo Will build opencv on ${{runner.os}}.
          bat build_windows.bat
          
      - name: Build on macOS.
        if: runner.os == 'macOS'
        run: |
          echo Will build opencv ${{ matrix.cv_version }} on ${{runner.os}}.
          sh build_unix.sh
