name: CMake

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build on Linux.
        if: runner.os == 'Linux'
        run: |
          sh build_unix.sh

      - name: Build on Windows.
        if: runner.os == 'Windows'
        run: |
          build_windows.bat

      - name: Build on macOS.
        if: runner.os == 'macOS'
        run: |
          sh build_unix.sh
